### PR TITLE
Save sounds and reuse them with new SfxrSound

### PR DESCRIPTION
**Pull request by Elideb**
Hi.

I've added the option in SfxrGenerator to store sounds to a file in Resources called "usfxr_sounds.txt". This sounds can be loaded, replaced and deleted from there using the generator window.

A new Serializable class SfxrSound can be used to play those saved sounds. If used as a variable, it exposes a drop down list to choose which sound it should play.

Using this new type, the SpaceGame PlayerCube code would look like this:
```csharp
using UnityEngine;
using System.Collections;

public class PlayerCube : MonoBehaviour {
	
	private const int PLAYER_SPEED = 50; // units per second
	private const int SHOTS_PER_SECOND = 20;
	private const int SHOTS_WITH_AUDIO_PER_SECOND = 10; // Doesn't play audio on EVERY shot otherwise it's just a cacophony of audio effects

	[SerializeField]
	private SfxrSound fireSound = null;

	private float lastTimeFired;
	private float lastTimeFiredAudio;

	void Update() {
		float speedPassed = Time.deltaTime;
		if (Input.GetKey(KeyCode.W) || Input.GetKey(KeyCode.UpArrow))    transform.Translate(0, PLAYER_SPEED * speedPassed, 0);
		if (Input.GetKey(KeyCode.S) || Input.GetKey(KeyCode.DownArrow))  transform.Translate(0, PLAYER_SPEED * -speedPassed, 0);
		if (Input.GetKey(KeyCode.A) || Input.GetKey(KeyCode.LeftArrow))  transform.Translate(PLAYER_SPEED * -speedPassed, 0, 0);
		if (Input.GetKey(KeyCode.D) || Input.GetKey(KeyCode.RightArrow)) transform.Translate(PLAYER_SPEED * speedPassed, 0, 0);

		if (Input.GetKey(KeyCode.Space) && Time.realtimeSinceStartup > lastTimeFired + 1f/SHOTS_PER_SECOND) SpawnBullet();
	}

	private void SpawnBullet() {
		// Fire
		float now = Time.realtimeSinceStartup;

		Instantiate(Resources.Load("Prefabs/Bullet"), transform.position, Quaternion.identity);
		lastTimeFired = now;

		if (now > lastTimeFiredAudio + 1f/SHOTS_WITH_AUDIO_PER_SECOND) {
			this.fireSound.Play();
			lastTimeFiredAudio = now;
		}
	}
}
```

And in the editor it would look like this:
usfxr_editsound

I think this functionality moves usfxr, which is already quite useful into full Unity usability level.

If you think I should modify something, or tweak the functionality, let me know and I'll gladly do it.

### CODE REVIEW

**Comment by Elideb** [comment]
And a couple of screen captures showing what the generator looks like now.

If the name does not exists, the current parameters can be saved as a new sound.
usfxr_save

If the name exists, it can be replaced with the current parameters, loaded or deleted.
usfxr_replace

**Comment by Elideb** [comment]
Hi again-

Apparently some of the editor functionality I've used (displayName, etc.) is only available in Unity 5. I'm converting that part of the code to 4.5 and will update the branch.

**Comment by zeh** [comment]
Hi Enrique, thanks so much for this. I'm away from home now, but I'll review it next week when I'm back. It looks great so far. 

Zeh

**Comment by Elideb** [comment]
Incompatibilities with Unity 4.5 fixed.

**Comment by zeh** [comment]
Awesome feature addition. I may tweak the UI a little bit once I work on this again, and I need to update the documentation to reflect this change. But it is a great change.

Thanks again Enrique.

**Comment by Elideb** [comment]
You're welcome.

If you want any further changes related, let me know. I'm using usfxr for the non-technical Unity classes I'm teaching, so any improvements to usability will help the students greatly.

**Pull request merged**
